# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='test_token',
            field=models.CharField(default=1, max_length=100, verbose_name='Hiddentoken'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Test Datetime'),
        ),
    ]
