# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('questionnaires', '0003_auto_20160910_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Choice Image'),
        ),
        migrations.AddField(
            model_name='choice',
            name='group',
            field=models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='group',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='intropage',
            field=models.TextField(blank=True, null=True, verbose_name='Introduction'),
        ),
    ]
